### PR TITLE
feat: preserve casing and handle npm namespace scenario

### PR DESCRIPTION
**Pull request by wood1986**
### Summary

For the inputs without namespace and `react-native-` scenario

```
yarn exec create-react-native-library WooDLibs
yarn exec v1.22.19
✔ What is the name of the npm package? … wood-libs
✔ What type of library do you want to develop? › Turbo module with backward compat (experimental)
```

image

For the inputs with namespace scenario

```
yarn exec create-react-native-library WooDLibs
yarn exec v1.22.19
✔ What is the name of the npm package? … @wood1986/wood-libs
✔ What type of library do you want to develop? › Turbo module with backward compat (experimental)
```

image

### CODE REVIEW

**Comment by wood1986** [comment]
Before I fix the tests, I want to get your approval

**Comment by wood1986** [comment]
ping

**Review by satya164 — CHANGES_REQUESTED** [review]
Hello, thank you for the PR. Can you add some comments above the code changes describing why we're doing it and what each of the replace is doing? I think currently it's not obvious just by reading the code why we're changing this.

Happy to merge after adding some comments

**Comment by satya164** [comment]
I'll work on getting this merged tomorrow

**Comment by satya164** [comment]
I refactored and implemented this in https://github.com/callstack/react-native-builder-bob/commit/4993bc9d200ea235456214f565184d9fd6dcf95f trying to preserve the namespace and spacing while still avoiding invalid input. I have added you as co-author of the commit since it's based on your work. Thanks again for the PR.

**Comment by wood1986** [comment]
Thanks for merge

**Pull request closed without merging**
