### PR TITLE
feat: add support for Java templates

### LINKED ISSUE #82: Java instead of Kotlin
Hi, is it possible that I use java instead of kotlin on Android side? If possible how can I do it? 

Thanks in advance

### PR DESCRIPTION
**Pull request by friederbluemle**
### Summary

This PR adds support for Java templates (both native module and native view types).

With this, Bob now supports all four possible combinations:

- Java + Objective-C
- Java + Swift
- Kotlin + Objective-C
- Kotlin + Swift

image

#### Commit Details

The PR head branch contains **3 commits** with incremental changes (one way dependency), best reviewed in succession.

##### `Move Kotlin templates to separate directory`

As the subject line states, this merely renames the existing Kotlin templates directory to `kotlin-library`, similar to the existing `objc-library`/`swift-library` categories. No functional changes, but prepares for the next commit with independent precursor work in `src/create.ts`.

##### `Add Java templates`

All new templates in `templates/java-library` and `templates/java-view-library`. Additional changes in `src/create.ts` to add the selection to the `bob create` command.

##### `Combine native and native-view into native-common`

This final commit again does not add any new functionality, but **removes** a large number of duplications by combining `native-library` and `native-view-library` into `native-common` (both on the Android and iOS side). I can move this one to a separate PR if preferred.

### Test plan

Use `bob create <name>` and select one of the new templates, verify that everything works.

Closes #82

<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest base branch. If it isn't, or if you want me to change anything, please let me know, and I will update the branch as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by kelsonpw** [comment]
Would love to see this get merged

**Comment by Krizzu** [comment]
@friederbluemle Great work on this one, much appreciated 🙏  !

> This final commit again does not add any new functionality, but removes a large number of duplications by combining native-library and native-view-library into native-common (both on the Android and iOS side). I can move this one to a separate PR if preferred.

I'm fine with having this one here. 

As a next improvement step, I'd think about having module type selection divided into categories (select either pure js or native, if native then either functional, view or both etc.), so that we're not lost in there. But that's another topic.

WDYT @satya164 ?

**Review by Krizzu — APPROVED** [review]

**Comment by friederbluemle** [comment]
> As a next improvement step, I'd think about having module type selection divided into categories (select either pure js or native, if native then either functional, view or both etc.), so that we're not lost in there. But that's another topic.

Yes, great point! I also had some ideas regarding this while working on the changes here. Like you said, it's another topic, and I wanted to keep the PR focused. Happy to discuss, help and contribute more in the future! :+1:

**Comment by shamilovtim** [comment]
Any status on getting this merged? I'm having to pull down the PR to bootstrap Java projects.

**Comment by friederbluemle** [comment]
@satya164 - If you have a few minutes can you please check this PR? Thanks! 🙏

**Comment by shamilovtim** [comment]
This PR really helped me out. Thanks!

**Review by shamilovtim — APPROVED** [review]
Currently using this in prod

**Comment by friederbluemle** [comment]
I just rebased this, which turned out to be a bit tricky and quite a bit of work after all the structural changes that got merged (especially dc56fc9). I would very much appreciate it if this could get merged/reviewed soon (before more changes are pushed to the main branch). 🙏

**Comment by satya164** [comment]
Hey, sorry for delay, I have been a bit busy with other stuff and also the pending monorepo reorg so haven't been able to check it. I'll try to check it soon.

**Comment by mlazari** [comment]
> Currently using this in prod

How do we use this before being merged and officially released?

**Comment by shamilovtim** [comment]
> > Currently using this in prod
> 
> How do we use this before being merged and officially released?

Pull the git repo, compile it, and run the same CLI commands you would as if you ran it from npm

**Comment by friederbluemle** [comment]
> > Currently using this in prod
> 
> How do we use this before being merged and officially released?

```
git clone -b java-template https://github.com/friederbluemle/react-native-builder-bob.git
cd react-native-builder-bob 
yarn
yarn --cwd packages/create-react-native-library
```

You should now have the executable script available in `packages/create-react-native-library/bin/`.

Run it directly from there to create a new `test` library (use type `native` or `native-view`):

```
packages/create-react-native-library/bin/create-react-native-library test --slug react-native-test --description test --author-name test --author-email test@test.com --author-url http://test --repo-url http://test --type native
```

**Comment by true-hamid** [comment]
> > > Currently using this in prod
> > 
> > 
> > How do we use this before being merged and officially released?
> 
> ```
> git clone -b java-template https://github.com/friederbluemle/react-native-builder-bob.git
> cd react-native-builder-bob 
> yarn
> yarn --cwd packages/create-react-native-library
> ```
> 
> You should now have the executable script available in `packages/create-react-native-library/bin/`.
> 
> Run it directly from there to create a new `test` library (use type `native` or `native-view`):
> 
> ```
> packages/create-react-native-library/bin/create-react-native-library test --slug react-native-test --description test --author-name test --author-email test@test.com --author-url http://test --repo-url http://test --type native
> ```

I see you removed/renamed you branch java-template, should we use the 'main' branch for this until it is released?
And thanks for this awesome contribution

**Comment by friederbluemle** [comment]
@true-hamid - The PR has already been merged. So until a new release has been published, you would need to use the default branch (`main`) in this repo.

Note that because a squash commit was used to merge the PR, the individual commits are no longer distinguishable in this repo. If you want to take a look at these, you can use the [`java-template-commits`](https://github.com/friederbluemle/react-native-builder-bob/tree/java-template-commits) branch that I pushed to my fork. Basically repeat the same steps as described above, but replace `java-template` with `java-template-commits`.

**Pull request merged**
